<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDbkxxvr\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDbkxxvr/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerDbkxxvr.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerDbkxxvr\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerDbkxxvr\srcProdProjectContainer([
    'container.build_hash' => 'Dbkxxvr',
    'container.build_id' => '683f27df',
    'container.build_time' => 1669704987,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDbkxxvr');
